enum SearchFormItemTypeEnum {
  SINGLE_SELECT = 'SINGLE_SELECT',
  SEARCH_KEY_INPUT = 'SEARCH_KEY_INPUT',
  RANGE_INPUT = 'RANGE_INPUT',
  SINGLE_CHECK_BOX_BUTTON = 'SINGLE_CHECK_BOX_BUTTON',
  RANGE_DATE_TIME_PICKER = 'RANGE_DATE_TIME_PICKER',
  TREE_V2 = 'TREE_V2',
}

export default SearchFormItemTypeEnum
